version: '3.3'
services:
  apiStone:
    container_name: apideteste
    image: apideteste
    environment:
      DATABASE_URL: "server=192.168.1.113;port=3306;database=copa;uid=root;password=;"
    ports:
      - "5001:5001"